config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :requests

      resources :approval_statuses

      resources :visitor_demographics

      resources :attraction_categories

      resources :user_types

      resources :bookmarks

      resources :exhibit_comments

      resources :exhibits

      resources :recordings

      resources :attraction_comments

      resources :attractions

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "users#index"
  resources :requests
  resources :approval_statuses
  resources :visitor_demographics
  resources :attraction_categories
  resources :user_types
  resources :bookmarks
  resources :exhibit_comments
  resources :exhibits
  resources :recordings
  resources :attraction_comments
  resources :attractions
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recording.rb
class Recording < ApplicationRecord
  mount_uploader :audio_upload, AudioUploadUploader

  # Direct associations

  belongs_to :exhibit

  # Indirect associations

  has_one    :attraction,
             through: :exhibit,
             source: :attraction

  # Validations

  # Scopes

  def to_s
    created_at
  end
end

app/controllers/api/v1/recordings_controller.rb
class Api::V1::RecordingsController < Api::V1::GraphitiController
  def index
    recordings = RecordingResource.all(params)
    respond_with(recordings)
  end

  def show
    recording = RecordingResource.find(params)
    respond_with(recording)
  end

  def create
    recording = RecordingResource.build(params)

    if recording.save
      render jsonapi: recording, status: :created
    else
      render jsonapi_errors: recording
    end
  end

  def update
    recording = RecordingResource.find(params)

    if recording.update_attributes
      render jsonapi: recording
    else
      render jsonapi_errors: recording
    end
  end

  def destroy
    recording = RecordingResource.find(params)

    if recording.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: recording
    end
  end
end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
  before_action :set_recording, only: %i[show edit update destroy]

  def index
    @q = Recording.ransack(params[:q])
    @recordings = @q.result(distinct: true).includes(:exhibit,
                                                     :attraction).page(params[:page]).per(10)
  end

  def show; end

  def new
    @recording = Recording.new
  end

  def edit; end

  def create
    @recording = Recording.new(recording_params)

    if @recording.save
      message = "Recording was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @recording, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @recording.update(recording_params)
      redirect_to @recording, notice: "Recording was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @recording.destroy
    message = "Recording was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to recordings_url, notice: message
    end
  end

  private

  def set_recording
    @recording = Recording.find(params[:id])
  end

  def recording_params
    params.require(:recording).permit(:exhibit_id, :audio_upload,
                                      :video_upload)
  end
end

app/views/recordings/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Recording #<%= recording.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Exhibit</dt>
      <dd>
        <% if @recording.exhibit.present? %>
          <%= link_to recording.exhibit, recording.exhibit %>
        <% end %>
      </dd>

      <dt>Audio upload</dt>
      <dd>
        <%= cl_image_tag @recording.audio_upload, class: "img-fluid" %>
      </dd>

      <dt>Video upload</dt>
      <dd><%= recording.video_upload %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back recording, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_recording_url(recording), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to recording, method: :delete, data: { confirm: "Do you really want to delete this recording?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(recording.updated_at) %> ago
  </div>
</div>

app/views/recordings/_form.html.erb
<% was_validated = recording.errors.any? %>

<%= form_with(model: recording, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% exhibit_class = "form-control" %>
    <% exhibit_was_invalid = recording.errors.include?(:exhibit) %>

    <% if was_validated %>
      <% if exhibit_was_invalid %>
        <% exhibit_class << " is-invalid" %>
      <% else %>
        <% exhibit_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :exhibit_id %>
    <%= f.collection_select :exhibit_id, Exhibit.all, :id, :to_s, {}, class: "form-control" %>
    <% if exhibit_was_invalid %>
      <% recording.errors.full_messages_for(:exhibit).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% audio_upload_class = "form-control" %>
    <% audio_upload_was_invalid = recording.errors.include?(:audio_upload) %>

    <% if was_validated %>
      <% if audio_upload_was_invalid %>
        <% audio_upload_class << " is-invalid" %>
      <% else %>
        <% audio_upload_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :audio_upload %>
    <%= f.file_field :audio_upload, class: "form-control" %>
    <% if audio_upload_was_invalid %>
      <% recording.errors.full_messages_for(:audio_upload).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% video_upload_class = "form-control" %>
    <% video_upload_was_invalid = recording.errors.include?(:video_upload) %>

    <% if was_validated %>
      <% if video_upload_was_invalid %>
        <% video_upload_class << " is-invalid" %>
      <% else %>
        <% video_upload_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :video_upload %>
    <%= f.text_field :video_upload, class: video_upload_class, placeholder: "Enter video upload" %>
    <% if video_upload_was_invalid %>
      <% recording.errors.full_messages_for(:video_upload).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/recordings/_list_item.html.erb
<%= link_to recording, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= recording %>
    <small class="text-muted">
      <%= time_ago_in_words(recording.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/recordings/_recording_attraction.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Attraction
  </div>

  <ul class="list-group list-group-flush">
    <% @recording.attraction.each do |attraction| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/attractions/<%= attraction.id %>">
          <%= attraction %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/recordings/_recordings_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "recordings_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :video_upload_cont, "Video upload contains" %>
    <%= f.text_field :video_upload_cont, :class => "form-control", :placeholder => "Video upload contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :exhibit_exhibit_name_cont, "Exhibit exhibit_name contains" %>
    <%= f.text_field :exhibit_exhibit_name_cont, :class => "form-control", :placeholder => "Exhibit exhibit_name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :attraction_attraction_name_cont, "Attraction attraction_name contains" %>
    <%= f.text_field :attraction_attraction_name_cont, :class => "form-control", :placeholder => "Attraction attraction_name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/recordings" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#recordings_filters">
  Show filters
</a>

app/views/recordings/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Recording #<%= @recording.id %>
      </h2>

      <div class="card-body">
        <%= render "form", recording: @recording %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recordings/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Recordings

      <%= link_to new_recording_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "recordings/recordings_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Recordings

        <%= link_to new_recording_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @recordings, partial: "list_item", as: :recording %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @recordings, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/recordings/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Recording
      </h2>

      <div class="card-body">
        <%= render "form", recording: @recording %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recordings/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @recording, partial: "card", as: :recording %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "recordings/recording_attraction" %>
  </div>
</div>