config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :requests

      resources :approval_statuses

      resources :visitor_demographics

      resources :attraction_categories

      resources :user_types

      resources :bookmarks

      resources :exhibit_comments

      resources :exhibits

      resources :recordings

      resources :attraction_comments

      resources :attractions

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "users#index"
  resources :requests
  resources :approval_statuses
  resources :visitor_demographics
  resources :attraction_categories
  resources :user_types
  resources :bookmarks
  resources :exhibit_comments
  resources :exhibits
  resources :recordings
  resources :attraction_comments
  resources :attractions
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/api/v1/approval_statuses_controller.rb
class Api::V1::ApprovalStatusesController < Api::V1::GraphitiController
  def index
    approval_statuses = ApprovalStatusResource.all(params)
    respond_with(approval_statuses)
  end

  def show
    approval_status = ApprovalStatusResource.find(params)
    respond_with(approval_status)
  end

  def create
    approval_status = ApprovalStatusResource.build(params)

    if approval_status.save
      render jsonapi: approval_status, status: :created
    else
      render jsonapi_errors: approval_status
    end
  end

  def update
    approval_status = ApprovalStatusResource.find(params)

    if approval_status.update_attributes
      render jsonapi: approval_status
    else
      render jsonapi_errors: approval_status
    end
  end

  def destroy
    approval_status = ApprovalStatusResource.find(params)

    if approval_status.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: approval_status
    end
  end
end

app/controllers/approval_statuses_controller.rb
class ApprovalStatusesController < ApplicationController
  before_action :set_approval_status, only: %i[show edit update destroy]

  def index
    @q = ApprovalStatus.ransack(params[:q])
    @approval_statuses = @q.result(distinct: true).includes(:requests).page(params[:page]).per(10)
  end

  def show
    @request = Request.new
  end

  def new
    @approval_status = ApprovalStatus.new
  end

  def edit; end

  def create
    @approval_status = ApprovalStatus.new(approval_status_params)

    if @approval_status.save
      redirect_to @approval_status,
                  notice: "Approval status was successfully created."
    else
      render :new
    end
  end

  def update
    if @approval_status.update(approval_status_params)
      redirect_to @approval_status,
                  notice: "Approval status was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @approval_status.destroy
    redirect_to approval_statuses_url,
                notice: "Approval status was successfully destroyed."
  end

  private

  def set_approval_status
    @approval_status = ApprovalStatus.find(params[:id])
  end

  def approval_status_params
    params.require(:approval_status).permit(:status_name)
  end
end

app/views/approval_statuses/_approval_status_requests.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Requests

    <a data-toggle="collapse" href="#approval_status_requests_new_form">
      Add request
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @approval_status.requests.each do |request| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to request, request %>

        <%= link_to request, method: :delete, data: { confirm: "Do you really want to delete this request" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="approval_status_requests_new_form">
        <%= render partial: "approval_statuses/approval_status_requests_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/approval_statuses/_approval_status_requests_new_form.html.erb
<%= form_with(model: @request, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :request_name %>

    <%= f.text_field :request_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :request_description %>
    <%= f.text_area :request_description, rows: "3", class: "form-control" %>
  </div>

  <%= f.hidden_field :status_id, value: @approval_status.id %>

  <div class="form-group">
    <%= f.label :approver_id %>

    <%= f.collection_select :approver_id, User.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :requestor_id %>

    <%= f.text_field :requestor_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :exhibit_id %>

    <%= f.collection_select :exhibit_id, Exhibit.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :attraction_id %>

    <%= f.collection_select :attraction_id, Attraction.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.submit "Create request", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/approval_statuses/_approval_statuses_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "approval_statuses_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :requests_request_name_cont, "Requests request_name contains" %>
    <%= f.text_field :requests_request_name_cont, :class => "form-control", :placeholder => "Requests request_name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/approval_statuses" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#approval_statuses_filters">
  Show filters
</a>

app/views/approval_statuses/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Approval Status #<%= approval_status.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Status name</dt>
      <dd><%= approval_status.status_name %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back approval_status, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_approval_status_url(approval_status), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to approval_status, method: :delete, data: { confirm: "Do you really want to delete this approval_status?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(approval_status.updated_at) %> ago
  </div>
</div>

app/views/approval_statuses/_form.html.erb
<% was_validated = approval_status.errors.any? %>

<%= form_with(model: approval_status, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% status_name_class = "form-control" %>
    <% status_name_was_invalid = approval_status.errors.include?(:status_name) %>

    <% if was_validated %>
      <% if status_name_was_invalid %>
        <% status_name_class << " is-invalid" %>
      <% else %>
        <% status_name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :status_name %>
    <%= f.select :status_name, options_for_select(ApprovalStatus.status_names.keys), {}, class: "form-control" %>
    <% if status_name_was_invalid %>
      <% approval_status.errors.full_messages_for(:status_name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/approval_statuses/_list_item.html.erb
<%= link_to approval_status, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= approval_status %>
    <small class="text-muted">
      <%= time_ago_in_words(approval_status.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/approval_statuses/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Approval Status #<%= @approval_status.id %>
      </h2>

      <div class="card-body">
        <%= render "form", approval_status: @approval_status %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/approval_statuses/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Approval Statuses

      <%= link_to new_approval_status_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "approval_statuses/approval_statuses_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Approval Statuses

        <%= link_to new_approval_status_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @approval_statuses, partial: "list_item", as: :approval_status %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @approval_statuses, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/approval_statuses/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Approval Status
      </h2>

      <div class="card-body">
        <%= render "form", approval_status: @approval_status %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/approval_statuses/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @approval_status, partial: "card", as: :approval_status %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "approval_statuses/approval_status_requests" %>
  </div>
</div>