config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :requests

      resources :approval_statuses

      resources :visitor_demographics

      resources :attraction_categories

      resources :user_types

      resources :bookmarks

      resources :exhibit_comments

      resources :exhibits

      resources :recordings

      resources :attraction_comments

      resources :attractions

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "users#index"
  resources :requests
  resources :approval_statuses
  resources :visitor_demographics
  resources :attraction_categories
  resources :user_types
  resources :bookmarks
  resources :exhibit_comments
  resources :exhibits
  resources :recordings
  resources :attraction_comments
  resources :attractions
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/attraction_category.rb
class AttractionCategory < ApplicationRecord
  enum category_description: { "museum_landmark_park_thrill_government_other" => 0 }

  enum category_type: { "landmark_museum_park_thrill" => 0 }

  # Direct associations

  has_many   :attractions,
             dependent: :destroy

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    category_type
  end
end

app/controllers/api/v1/attraction_categories_controller.rb
class Api::V1::AttractionCategoriesController < Api::V1::GraphitiController
  def index
    attraction_categories = AttractionCategoryResource.all(params)
    respond_with(attraction_categories)
  end

  def show
    attraction_category = AttractionCategoryResource.find(params)
    respond_with(attraction_category)
  end

  def create
    attraction_category = AttractionCategoryResource.build(params)

    if attraction_category.save
      render jsonapi: attraction_category, status: :created
    else
      render jsonapi_errors: attraction_category
    end
  end

  def update
    attraction_category = AttractionCategoryResource.find(params)

    if attraction_category.update_attributes
      render jsonapi: attraction_category
    else
      render jsonapi_errors: attraction_category
    end
  end

  def destroy
    attraction_category = AttractionCategoryResource.find(params)

    if attraction_category.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: attraction_category
    end
  end
end

app/controllers/attraction_categories_controller.rb
class AttractionCategoriesController < ApplicationController
  before_action :set_attraction_category,
                only: %i[show edit update destroy]

  def index
    @q = AttractionCategory.ransack(params[:q])
    @attraction_categories = @q.result(distinct: true).includes(:attractions).page(params[:page]).per(10)
  end

  def show
    @attraction = Attraction.new
  end

  def new
    @attraction_category = AttractionCategory.new
  end

  def edit; end

  def create
    @attraction_category = AttractionCategory.new(attraction_category_params)

    if @attraction_category.save
      redirect_to @attraction_category,
                  notice: "Attraction category was successfully created."
    else
      render :new
    end
  end

  def update
    if @attraction_category.update(attraction_category_params)
      redirect_to @attraction_category,
                  notice: "Attraction category was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @attraction_category.destroy
    redirect_to attraction_categories_url,
                notice: "Attraction category was successfully destroyed."
  end

  private

  def set_attraction_category
    @attraction_category = AttractionCategory.find(params[:id])
  end

  def attraction_category_params
    params.require(:attraction_category).permit(:category_type,
                                                :category_description, :target_demographic)
  end
end

app/views/attraction_categories/_attraction_categories_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "attraction_categories_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :target_demographic_cont, "Target demographic contains" %>
    <%= f.text_field :target_demographic_cont, :class => "form-control", :placeholder => "Target demographic contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :attractions_attraction_name_cont, "Attractions attraction_name contains" %>
    <%= f.text_field :attractions_attraction_name_cont, :class => "form-control", :placeholder => "Attractions attraction_name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/attraction_categories" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#attraction_categories_filters">
  Show filters
</a>

app/views/attraction_categories/_attraction_category_attractions.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Attractions

    <a data-toggle="collapse" href="#attraction_category_attractions_new_form">
      Add attraction
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @attraction_category.attractions.each do |attraction| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to attraction, attraction %>

        <%= link_to attraction, method: :delete, data: { confirm: "Do you really want to delete this attraction" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="attraction_category_attractions_new_form">
        <%= render partial: "attraction_categories/attraction_category_attractions_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/attraction_categories/_attraction_category_attractions_new_form.html.erb
<%= form_with(model: @attraction, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :attraction_name %>

    <%= f.text_field :attraction_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :attraction_location %>

    <%= f.text_field :attraction_location, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :attraction_description %>
    <%= f.text_area :attraction_description, rows: "3", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :attraction_image %>

    <%= f.file_field :attraction_image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :status_id %>

    <%= f.text_field :status_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :phone_number %>

    <%= f.text_field :phone_number, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email_address %>

    <%= f.text_field :email_address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :hours_of_operation %>

    <%= f.text_field :hours_of_operation, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :cost_of_entry %>

    <%= f.text_field :cost_of_entry, class: "form-control" %>
  </div>

  <%= f.hidden_field :attraction_category_id, value: @attraction_category.id %>

  <%= f.submit "Create attraction", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/attraction_categories/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Attraction Category #<%= attraction_category.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Category type</dt>
      <dd><%= attraction_category.category_type %></dd>

      <dt>Category description</dt>
      <dd><%= attraction_category.category_description %></dd>

      <dt>Target demographic</dt>
      <dd><%= attraction_category.target_demographic %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back attraction_category, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_attraction_category_url(attraction_category), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to attraction_category, method: :delete, data: { confirm: "Do you really want to delete this attraction_category?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(attraction_category.updated_at) %> ago
  </div>
</div>

app/views/attraction_categories/_form.html.erb
<% was_validated = attraction_category.errors.any? %>

<%= form_with(model: attraction_category, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% category_type_class = "form-control" %>
    <% category_type_was_invalid = attraction_category.errors.include?(:category_type) %>

    <% if was_validated %>
      <% if category_type_was_invalid %>
        <% category_type_class << " is-invalid" %>
      <% else %>
        <% category_type_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :category_type %>
    <%= f.select :category_type, options_for_select(AttractionCategory.category_types.keys), {}, class: "form-control" %>
    <% if category_type_was_invalid %>
      <% attraction_category.errors.full_messages_for(:category_type).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% category_description_class = "form-control" %>
    <% category_description_was_invalid = attraction_category.errors.include?(:category_description) %>

    <% if was_validated %>
      <% if category_description_was_invalid %>
        <% category_description_class << " is-invalid" %>
      <% else %>
        <% category_description_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :category_description %>
    <%= f.select :category_description, options_for_select(AttractionCategory.category_descriptions.keys), {}, class: "form-control" %>
    <% if category_description_was_invalid %>
      <% attraction_category.errors.full_messages_for(:category_description).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% target_demographic_class = "form-control" %>
    <% target_demographic_was_invalid = attraction_category.errors.include?(:target_demographic) %>

    <% if was_validated %>
      <% if target_demographic_was_invalid %>
        <% target_demographic_class << " is-invalid" %>
      <% else %>
        <% target_demographic_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :target_demographic %>
    <%= f.text_field :target_demographic, class: target_demographic_class, placeholder: "Enter target demographic" %>
    <% if target_demographic_was_invalid %>
      <% attraction_category.errors.full_messages_for(:target_demographic).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/attraction_categories/_list_item.html.erb
<%= link_to attraction_category, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= attraction_category %>
    <small class="text-muted">
      <%= time_ago_in_words(attraction_category.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/attraction_categories/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Attraction Category #<%= @attraction_category.id %>
      </h2>

      <div class="card-body">
        <%= render "form", attraction_category: @attraction_category %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/attraction_categories/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Attraction Categories

      <%= link_to new_attraction_category_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "attraction_categories/attraction_categories_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Attraction Categories

        <%= link_to new_attraction_category_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @attraction_categories, partial: "list_item", as: :attraction_category %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @attraction_categories, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/attraction_categories/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Attraction Category
      </h2>

      <div class="card-body">
        <%= render "form", attraction_category: @attraction_category %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/attraction_categories/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @attraction_category, partial: "card", as: :attraction_category %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "attraction_categories/attraction_category_attractions" %>
  </div>
</div>