config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :requests

      resources :approval_statuses

      resources :visitor_demographics

      resources :attraction_categories

      resources :user_types

      resources :bookmarks

      resources :exhibit_comments

      resources :exhibits

      resources :recordings

      resources :attraction_comments

      resources :attractions

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "users#index"
  resources :requests
  resources :approval_statuses
  resources :visitor_demographics
  resources :attraction_categories
  resources :user_types
  resources :bookmarks
  resources :exhibit_comments
  resources :exhibits
  resources :recordings
  resources :attraction_comments
  resources :attractions
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/api/v1/attractions_controller.rb
class Api::V1::AttractionsController < Api::V1::GraphitiController
  def index
    attractions = AttractionResource.all(params)
    respond_with(attractions)
  end

  def show
    attraction = AttractionResource.find(params)
    respond_with(attraction)
  end

  def create
    attraction = AttractionResource.build(params)

    if attraction.save
      render jsonapi: attraction, status: :created
    else
      render jsonapi_errors: attraction
    end
  end

  def update
    attraction = AttractionResource.find(params)

    if attraction.update_attributes
      render jsonapi: attraction
    else
      render jsonapi_errors: attraction
    end
  end

  def destroy
    attraction = AttractionResource.find(params)

    if attraction.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: attraction
    end
  end
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :set_attraction, only: %i[show edit update destroy]

  def index
    @q = Attraction.ransack(params[:q])
    @attractions = @q.result(distinct: true).includes(:attraction_comments,
                                                      :exhibits, :bookmarks, :requests, :attraction_category, :modification_requests, :recordings, :users).page(params[:page]).per(10)
    @location_hash = Gmaps4rails.build_markers(@attractions.where.not(attraction_location_latitude: nil)) do |attraction, marker|
      marker.lat attraction.attraction_location_latitude
      marker.lng attraction.attraction_location_longitude
    end
  end

  def show
    @request = Request.new
    @bookmark = Bookmark.new
    @exhibit = Exhibit.new
    @attraction_comment = AttractionComment.new
  end

  def new
    @attraction = Attraction.new
  end

  def edit; end

  def create
    @attraction = Attraction.new(attraction_params)

    if @attraction.save
      message = "Attraction was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @attraction, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @attraction.update(attraction_params)
      redirect_to @attraction, notice: "Attraction was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @attraction.destroy
    message = "Attraction was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to attractions_url, notice: message
    end
  end

  private

  def set_attraction
    @attraction = Attraction.find(params[:id])
  end

  def attraction_params
    params.require(:attraction).permit(:attraction_name,
                                       :attraction_location, :attraction_description, :attraction_image, :status_id, :phone_number, :email_address, :hours_of_operation, :cost_of_entry, :attraction_category_id)
  end
end

app/views/attractions/_all_photos_map.html.erb
<div id="location_map" style="height: 480px;"></div>
<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'location_map'}}, function(){
    markers = handler.addMarkers(<%= raw @location_hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/attractions/_attraction_attraction_comments_new_form.html.erb
<%= form_with(model: @attraction_comment, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :commenter_id %>

    <%= f.collection_select :commenter_id, User.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :attraction_id, value: @attraction.id %>

  <div class="form-group">
    <%= f.label :comment_text %>
    <%= f.text_area :comment_text, rows: "3", class: "form-control" %>
  </div>

  <%= f.submit "Create attraction comment", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/attractions/_attraction_bookmarks.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Bookmarks

    <a data-toggle="collapse" href="#attraction_bookmarks_new_form">
      Add bookmark
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @attraction.bookmarks.each do |bookmark| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to bookmark, bookmark %>

        <%= link_to bookmark, method: :delete, data: { confirm: "Do you really want to delete this bookmark" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="attraction_bookmarks_new_form">
        <%= render partial: "attractions/attraction_bookmarks_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/attractions/_attraction_exhibits_new_form.html.erb
<%= form_with(model: @exhibit, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :exhibit_name %>

    <%= f.text_field :exhibit_name, class: "form-control" %>
  </div>

  <%= f.hidden_field :attraction_id, value: @attraction.id %>

  <div class="form-group">
    <%= f.label :exhibit_description %>
    <%= f.text_area :exhibit_description, rows: "3", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :exhibit_image %>

    <%= f.file_field :exhibit_image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :exhibit_location %>

    <%= f.text_field :exhibit_location, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :status_id %>

    <%= f.text_field :status_id, class: "form-control" %>
  </div>

  <%= f.submit "Create exhibit", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/attractions/_attraction_recordings.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Recordings
  </div>

  <ul class="list-group list-group-flush">
    <% @attraction.recordings.each do |recording| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/recordings/<%= recording.id %>">
          <%= recording %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/attractions/_attraction_requests.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Requests

    <a data-toggle="collapse" href="#attraction_requests_new_form">
      Add request
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @attraction.requests.each do |request| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to request, request %>

        <%= link_to request, method: :delete, data: { confirm: "Do you really want to delete this request" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="attraction_requests_new_form">
        <%= render partial: "attractions/attraction_requests_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/attractions/_attraction_requests_new_form.html.erb
<%= form_with(model: @request, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :request_name %>

    <%= f.text_field :request_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :request_description %>
    <%= f.text_area :request_description, rows: "3", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :status_id %>

    <%= f.collection_select :status_id, ApprovalStatus.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :approver_id %>

    <%= f.collection_select :approver_id, User.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :requestor_id %>

    <%= f.text_field :requestor_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :exhibit_id %>

    <%= f.collection_select :exhibit_id, Exhibit.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :attraction_id, value: @attraction.id %>

  <%= f.submit "Create request", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/attractions/_attractions_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "attractions_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :attraction_name_cont, "Attraction name contains" %>
    <%= f.text_field :attraction_name_cont, :class => "form-control", :placeholder => "Attraction name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :cost_of_entry_cont, "Cost of entry contains" %>
    <%= f.text_field :cost_of_entry_cont, :class => "form-control", :placeholder => "Cost of entry contains" %>
  </div>

  <div class="form-group">
    <%= f.label :hours_of_operation_cont, "Hours of operation contains" %>
    <%= f.text_field :hours_of_operation_cont, :class => "form-control", :placeholder => "Hours of operation contains" %>
  </div>

  <div class="form-group">
    <%= f.label :email_address_cont, "Email address contains" %>
    <%= f.text_field :email_address_cont, :class => "form-control", :placeholder => "Email address contains" %>
  </div>

  <div class="form-group">
    <%= f.label :phone_number_cont, "Phone number contains" %>
    <%= f.text_field :phone_number_cont, :class => "form-control", :placeholder => "Phone number contains" %>
  </div>

  <div class="form-group">
    <%= f.label :status_id, "Status" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :status_id_gteq, :class => "form-control", :placeholder => "Status greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :status_id_lteq, :class => "form-control", :placeholder => "Status less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :attraction_description_cont, "Attraction description contains" %>
    <%= f.text_field :attraction_description_cont, :class => "form-control", :placeholder => "Attraction description contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :exhibits_exhibit_name_cont, "Exhibits exhibit_name contains" %>
    <%= f.text_field :exhibits_exhibit_name_cont, :class => "form-control", :placeholder => "Exhibits exhibit_name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :requests_request_name_cont, "Requests request_name contains" %>
    <%= f.text_field :requests_request_name_cont, :class => "form-control", :placeholder => "Requests request_name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :modification_requests_request_name_cont, "Modification requests request_name contains" %>
    <%= f.text_field :modification_requests_request_name_cont, :class => "form-control", :placeholder => "Modification requests request_name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Recording Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='recordingsgteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :recordings_created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Recording Created at greater than or equal to", :data => {:target => '#recordingsgteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#recordingsgteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='recordingslteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :recordings_created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Recording Created at less than or equal to", :data => {:target => '#recordingslteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#recordingslteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#recordingsgteqcreated_atPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#recordingslteqcreated_atPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#recordingsgteqcreated_atPicker').on("dp.change", function (e) {
              $('#recordingslteqcreated_atPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#recordingslteqcreated_atPicker').on("dp.change", function (e) {
              $('#recordingsgteqcreated_atPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :users_first_name_cont, "Users first_name contains" %>
    <%= f.text_field :users_first_name_cont, :class => "form-control", :placeholder => "Users first_name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/attractions" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#attractions_filters">
  Show filters
</a>

app/views/attractions/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Attraction #<%= attraction.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Attraction name</dt>
      <dd><%= attraction.attraction_name %></dd>

      <dt>Attraction location</dt>
      <dd>
        <div>
          <%= render partial: "attractions/one_photo_map" %>
        </div>
      </dd>

      <dt>Attraction description</dt>
      <dd><%= attraction.attraction_description %></dd>

      <dt>Attraction image</dt>
      <dd>
        <%= cl_image_tag @attraction.attraction_image, class: "img-fluid" %>
      </dd>

      <dt>Status</dt>
      <dd><%= attraction.status_id %></dd>

      <dt>Phone number</dt>
      <dd><%= attraction.phone_number %></dd>

      <dt>Email address</dt>
      <dd><%= attraction.email_address %></dd>

      <dt>Hours of operation</dt>
      <dd><%= attraction.hours_of_operation %></dd>

      <dt>Cost of entry</dt>
      <dd><%= attraction.cost_of_entry %></dd>

      <dt>Attraction category</dt>
      <dd>
        <% if @attraction.attraction_category.present? %>
          <%= link_to attraction.attraction_category, attraction.attraction_category %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back attraction, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_attraction_url(attraction), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to attraction, method: :delete, data: { confirm: "Do you really want to delete this attraction?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(attraction.updated_at) %> ago
  </div>
</div>

app/views/attractions/_form.html.erb
<% was_validated = attraction.errors.any? %>

<%= form_with(model: attraction, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% attraction_name_class = "form-control" %>
    <% attraction_name_was_invalid = attraction.errors.include?(:attraction_name) %>

    <% if was_validated %>
      <% if attraction_name_was_invalid %>
        <% attraction_name_class << " is-invalid" %>
      <% else %>
        <% attraction_name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :attraction_name %>
    <%= f.text_field :attraction_name, class: attraction_name_class, placeholder: "Enter attraction name" %>
    <% if attraction_name_was_invalid %>
      <% attraction.errors.full_messages_for(:attraction_name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% attraction_location_class = "form-control" %>
    <% attraction_location_was_invalid = attraction.errors.include?(:attraction_location) %>

    <% if was_validated %>
      <% if attraction_location_was_invalid %>
        <% attraction_location_class << " is-invalid" %>
      <% else %>
        <% attraction_location_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :attraction_location %>
    <%= f.text_field :attraction_location, class: attraction_location_class, placeholder: "Enter attraction location" %>
    <% if attraction_location_was_invalid %>
      <% attraction.errors.full_messages_for(:attraction_location).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% attraction_description_class = "form-control" %>
    <% attraction_description_was_invalid = attraction.errors.include?(:attraction_description) %>

    <% if was_validated %>
      <% if attraction_description_was_invalid %>
        <% attraction_description_class << " is-invalid" %>
      <% else %>
        <% attraction_description_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :attraction_description %>
    <%= f.text_area :attraction_description, class: attraction_description_class, placeholder: "Enter attraction description" %>
    <% if attraction_description_was_invalid %>
      <% attraction.errors.full_messages_for(:attraction_description).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% attraction_image_class = "form-control" %>
    <% attraction_image_was_invalid = attraction.errors.include?(:attraction_image) %>

    <% if was_validated %>
      <% if attraction_image_was_invalid %>
        <% attraction_image_class << " is-invalid" %>
      <% else %>
        <% attraction_image_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :attraction_image %>
    <%= f.file_field :attraction_image, class: "form-control" %>
    <% if attraction_image_was_invalid %>
      <% attraction.errors.full_messages_for(:attraction_image).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% status_class = "form-control" %>
    <% status_was_invalid = attraction.errors.include?(:status) %>

    <% if was_validated %>
      <% if status_was_invalid %>
        <% status_class << " is-invalid" %>
      <% else %>
        <% status_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :status_id %>
    <%= f.number_field :status_id, class: status_class, placeholder: "Enter status" %>
    <% if status_was_invalid %>
      <% attraction.errors.full_messages_for(:status).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% phone_number_class = "form-control" %>
    <% phone_number_was_invalid = attraction.errors.include?(:phone_number) %>

    <% if was_validated %>
      <% if phone_number_was_invalid %>
        <% phone_number_class << " is-invalid" %>
      <% else %>
        <% phone_number_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: phone_number_class, placeholder: "Enter phone number" %>
    <% if phone_number_was_invalid %>
      <% attraction.errors.full_messages_for(:phone_number).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% email_address_class = "form-control" %>
    <% email_address_was_invalid = attraction.errors.include?(:email_address) %>

    <% if was_validated %>
      <% if email_address_was_invalid %>
        <% email_address_class << " is-invalid" %>
      <% else %>
        <% email_address_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :email_address %>
    <%= f.text_field :email_address, class: email_address_class, placeholder: "Enter email address" %>
    <% if email_address_was_invalid %>
      <% attraction.errors.full_messages_for(:email_address).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% hours_of_operation_class = "form-control" %>
    <% hours_of_operation_was_invalid = attraction.errors.include?(:hours_of_operation) %>

    <% if was_validated %>
      <% if hours_of_operation_was_invalid %>
        <% hours_of_operation_class << " is-invalid" %>
      <% else %>
        <% hours_of_operation_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :hours_of_operation %>
    <%= f.text_field :hours_of_operation, class: hours_of_operation_class, placeholder: "Enter hours of operation" %>
    <% if hours_of_operation_was_invalid %>
      <% attraction.errors.full_messages_for(:hours_of_operation).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% cost_of_entry_class = "form-control" %>
    <% cost_of_entry_was_invalid = attraction.errors.include?(:cost_of_entry) %>

    <% if was_validated %>
      <% if cost_of_entry_was_invalid %>
        <% cost_of_entry_class << " is-invalid" %>
      <% else %>
        <% cost_of_entry_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :cost_of_entry %>
    <%= f.text_field :cost_of_entry, class: cost_of_entry_class, placeholder: "Enter cost of entry" %>
    <% if cost_of_entry_was_invalid %>
      <% attraction.errors.full_messages_for(:cost_of_entry).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% attraction_category_class = "form-control" %>
    <% attraction_category_was_invalid = attraction.errors.include?(:attraction_category) %>

    <% if was_validated %>
      <% if attraction_category_was_invalid %>
        <% attraction_category_class << " is-invalid" %>
      <% else %>
        <% attraction_category_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :attraction_category_id %>
    <%= f.collection_select :attraction_category_id, AttractionCategory.all, :id, :to_s, {}, class: "form-control" %>
    <% if attraction_category_was_invalid %>
      <% attraction.errors.full_messages_for(:attraction_category).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/attractions/_list_item.html.erb
<%= link_to attraction, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= attraction %>
    <small class="text-muted">
      <%= time_ago_in_words(attraction.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/attractions/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Attractions

      <%= link_to new_attraction_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "attractions/attractions_search_form" %>
  </div>
</div>

<div class="row mb-3">
  <div class="col-md-12">
    <%= render partial: "attractions/all_photos_map" %>
  </div>
</div>


<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Attractions

        <%= link_to new_attraction_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @attractions, partial: "list_item", as: :attraction %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @attractions, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>